### PR TITLE
Resolves #10 Missing spring-cloud-stream-test-support dependency

### LINKED ISSUE #10: [TCP] Compilation failure due to a missing spring-cloud-stream-test-support dependency

### PR DESCRIPTION
**Pull request by tzolov**
Resolves #10

### CODE REVIEW

**Comment by artembilan** [comment]
Why can’t we have this dependency on the apps core level? It’s going to be pain to add it to each project...
Thanks

**Comment by tzolov** [comment]
@sobychacko what do you think about @artembilan suggestion?

**Comment by olegz** [comment]
Since we're deprecating Test binder all together, I'd say core level is fine as log as we're ready at some point in the future to migrate all apps to use new Test Binder.

**Comment by tzolov** [comment]
Looking at the apps dependency graph: https://spring.io/admin/blog/3163-spring-cloud-stream-app-starters-bom-dependencies 
It looks to me that even if we add `org.springframework.cloud:spring-cloud-stream-test-support:test` to app's core's pom (https://github.com/spring-cloud-stream-app-starters/core/blob/master/pom.xml) because of the `test` scope it will not be transferred to children apps?

**Pull request merged**
